spin_manifest_version = 2

[application]
name = "test"
version = "0.1.0"
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "test"

[component.test]
source = "component.wasm"
allowed_outbound_hosts = ["*://*:*"]
key_value_stores = ["default"]
ai_models = ["llama2-chat"]
sqlite_databases = ["default"]
[component.test.variables]
test = "try"
[component.test.build]
command = "npx webpack && npx j2w -i dist.js -n spin-http && npx webpack -c webpack.client.js"

[[trigger.http]]
route = "/static/..."
component = "static-fs"

[component.static-fs]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "dist", destination = "/" }]
